apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment1
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: front1
        image: httpd:latest
        ports:
          - containerPort: 80
